### ISSUE TITLE
生成的api模块与原模块包名冲突

### ISSUE THREAD

**Issue by cbfg5210** [qiugang/APIModuleDemo#1]
你好，我在我的项目中使用了include-api插件，运行项目的时候提示：Program type already present: com.xx.BuildConfig。生成的api模块与原模块包名冲突了，这个问题有遇到吗？应该怎么解决这个问题？

**Comment by qiugang** [comment]
BuildConfig 类是自动生成的，你是否有在某个地方既依赖了原有 module，还 includeApi("$module") 了呢？

**Comment by cbfg5210** [comment]
我运行APIModuleDemo项目也有出现了这个问题：
![tim 20190114154549](https://user-images.githubusercontent.com/12880545/51100973-95e88680-1813-11e9-916e-248cc1bffaab.png)
![tim 20190114155706](https://user-images.githubusercontent.com/12880545/51101366-5884f880-1815-11e9-87ab-8b08a3b2722d.png)

**Comment by qiugang** [comment]
使用 ```gradlew assembleDebug``` 命令尝试一下呢，我刚才 build 了一下是 ok 的。

**Comment by cbfg5210** [comment]
> 使用 `gradlew assembleDebug` 命令尝试一下呢，我刚才 build 了一下是 ok 的。

我用的as是3.2.1 ：
![tim 20190114162436](https://user-images.githubusercontent.com/12880545/51102222-0cd44e00-1819-11e9-99b3-3cf7180ef025.png)

**Comment by qiugang** [comment]
目前将 api module 类型从 Android Library 降级为了 Java / Kotlin Library,   Android Library 的支持将在后续版本提供。

**Comment by qiugang** [comment]
最新 master 已支持 api module 为 Android Library
